default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mira_dev

test:
  <<: *default
  database: mira_test

production:
  <<: *default
  database: mira_prod
